name: Week 3 - Task 15

run-name: Running test for week 3 and task 15

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/tests/week3_tasks/13-15-inventory-page/15*.js'
jobs:
  week3-task15:
    uses: ./.github/workflows/reusable.yml
    with:
      npm-command: 'test-15'
