name: Week 3 - Task 9

run-name: Running test for week 3 and task 9

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/tests/week3_tasks/9*.js'
jobs:
  week3-task9:
    uses: ./.github/workflows/reusable.yml
    with:
      npm-command: 'test-9'
