name: Week 2 - Task 2

run-name: Running test for week 2 and task 2

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/tests/week2_tasks/2*.js'
jobs:
  week2-task2:
    uses: ./.github/workflows/reusable.yml
    with:
      npm-command: 'test-2'
